# Generated by Django 5.0.2 on 2024-03-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons', models.CharField(max_length=250, verbose_name='Data1')),
                ('title', models.DateField(verbose_name='Data3')),
            ],
        ),
    ]
