# Generated by Django 5.0.2 on 2024-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datai',
            options={'verbose_name': 'Datei', 'verbose_name_plural': 'Dateis'},
        ),
        migrations.AddField(
            model_name='datai',
            name='title1',
            field=models.CharField(default='', max_length=250, verbose_name='Data2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datai',
            name='title2',
            field=models.TextField(default='', verbose_name='Data3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datai',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Data'),
        ),
    ]
