# Generated by Django 5.0.2 on 2024-03-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0002_alter_datai_options_datai_title1_datai_title2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffractionGrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('absorption', models.FloatField()),
                ('y', models.IntegerField()),
                ('gap_num', models.IntegerField()),
                ('gap_size', models.IntegerField()),
                ('gap_space', models.IntegerField()),
                ('potential_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MultisliceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('wavelength', models.FloatField()),
                ('phase', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Datai',
        ),
    ]
